save_data: _{}/nmt.{convs2s,rnn,transformer}
save_model: _{}/nmt.{convs2s,rnn,transformer}.model
src_vocab: _{}/nmt.{convs2s,rnn,transformer}.vocab.src
tgt_vocab: _{}/nmt.{convs2s,rnn,transformer}.vocab.tgt
overwrite: False #True raise warning, False >> raise exception
data:
  corpus_1:
    path_src: _{}/src-train.txt
    path_tgt: _{}/tgt-train.txt
    transforms: []
  valid:
    path_src: _{}/src-val.txt
    path_tgt: _{}/tgt-val.txt
vocab_sample_limit: -1
#src_embeddings: ../output/nmt/run/example.vocab.src.emb
#tgt_embeddings: ../output/nmt/run/example.vocab.tgt.emb

seed: _{seed}

early_stopping: _{es}
early_stopping_criteria: accuracy
dropout: 0.2
word_vec_size: 128 # same as embedding dimension _{d}

# Batching
world_size: 1 # Train on a single GPU
gpu_ranks: _{acceleration}
#world_size: 2
#gpu_ranks: [0, 1]
num_workers: 8
batch_size: _{b}
#bucket_size: 832
#valid_batch_size: defaults to ${batch_size}

# # Where to save the checkpoints and common hyperparameters
keep_checkpoint: -1
#train_steps: 100 # default behaviour based on roughly train_steps = (total_training_examples) / batch_size) * num_epochs
#train_epochs: _{e} # change the default to n_epoch
save_checkpoint_steps: 1 #_{spe} but here is per batch
valid_steps: 1
#report_every: 1

# Optimization
model_dtype: "fp16"
optim: adam
weight_decay: 0.0001
learning_rate: _{lr} #0.001
adam_beta1: 0.9
adam_beta2: 0.98

#start_decay_steps: 50
#decay_steps: 50

# copy_attn: 'true'
# global_attention: mlp
# reuse_copy_attn: 'true'
# bridge: 'true'

encoder_type: _{enc} #cnn,rnn,transformer
decoder_type: _{dec} #could be different

## ConvS2S with Attention Configuration Template
cnn_size: 128 # same as hidden size
cnn_kernel_width: 3
layers: 4

## RNN with Attention Configuration Template
rnn_type: LSTM
rnn_size: 128
input_feed: 1
enc_layers: 4
dec_layers: 4

## Transformer with Attention Configuration Template
warmup_steps: 501 # transformer
position_encoding: False # for now, we don't want purticular order in input skills and output members. But we can experiment on True
hidden_size: 128
transformer_ff: 512
attention_dropout: 0.2
#enc_layers: 8
#dec_layers: 8
heads: 8