## Transformer Configuration

## Where the samples will be written
save_data: ../output/nmt/run/transformer

## Where the vocab(s) will be written
src_vocab: ../output/nmt/run/transformer.vocab.src
tgt_vocab: ../output/nmt/run/transformer.vocab.tgt

# Prevent overwriting existing files in the folder
overwrite: True

# Corpus opts:
data:
    corpus_1:
        path_src: ../output/nmt/src-train.txt
        path_tgt: ../output/nmt/tgt-train.txt
        weight: 1
    valid:
        path_src: ../output/nmt/src-val.txt
        path_tgt: ../output/nmt/tgt-val.txt

# Vocabulary files that were just created
src_vocab: ../output/nmt/run/transformer.vocab.src
tgt_vocab: ../output/nmt/run/transformer.vocab.tgt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: ../output/nmt/run/transformer_model
save_checkpoint_steps: 500
train_steps: 1000

keep_checkpoint: -1
seed: 0
valid_steps: 1000
report_every: 1000

# Model hyperparameters
word_vec_size: 512
hidden_size: 512
transformer_ff: 2048
heads: 8
layers: 6  # Transformers often use 6 or more layers effectively

encoder_type: transformer
decoder_type: transformer
position_encoding: True

optim: adam
learning_rate: 0.0005  # Reduced learning rate for stability
learning_rate_decay: 0.95  # Slower decay
start_decay_steps: 100  # Delay decay start
decay_steps: 100  # Decay less frequently
batch_size: 16  # Increased batch size for better gradient estimates
dropout: 0.3  # Slightly lower dropout rate to retain more information
