## Transformer Configuration

## Inspired by the Google setup
## from https://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-train-the-transformer-model

## Where the samples will be written
save_data: ../output/nmt/run/transformer

## Where the vocab(s) will be written
src_vocab: ../output/nmt/run/transformer.vocab.src
tgt_vocab: ../output/nmt/run/transformer.vocab.tgt

# Prevent overwriting existing files in the folder
overwrite: True

# Corpus opts:
data:
  corpus_1:
    path_src: ../output/nmt/src-train.txt
    path_tgt: ../output/nmt/tgt-train.txt
    weight: 1
  valid:
    path_src: ../output/nmt/src-val.txt
    path_tgt: ../output/nmt/tgt-val.txt

# --------------------------------------------------------------------------

# General opts
save_model: ../output/nmt/run/transformer_model
save_checkpoint_steps: 10000
valid_steps: 10000
train_steps: 300000

# Batching
bucket_size: 262144
world_size: 1
gpu_ranks: [0]
num_workers: 4
batch_type: "tokens"
batch_size: 512
valid_batch_size: 1024
accum_steps: [0]

# Optimization
model_dtype: "fp16"
optim: adam
weight_decay: 0.0001
learning_rate: 0.0005
warmup_steps: 16000
decay_method: "noam"
adam_beta2: 0.998
learning_rate_decay: 0.8
decay_steps: 10000
max_grad_norm: 0
label_smoothing: 0.05
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model hyperparameters
encoder_type: transformer
decoder_type: transformer
position_encoding: false
max_relative_positions: 20
enc_layers: 4
dec_layers: 4
heads: 8
hidden_size: 512
word_vec_size: 512
transformer_ff: 3072
dropout: [0.2]
attention_dropout: [0.2]

beam_size: 5
length_penalty: 1.0
